# This file is for teaching kustomize how to substitute name and namespace reference in CRD
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: CustomResourceDefinition
    version: v1
    group: apiextensions.k8s.io
    path: spec/conversion/webhook/clientConfig/service/name
- kind: CouchbaseCluster
  version: v2
  group: couchbase.com
  fieldSpecs:
  - kind: CouchbaseIndexSet
    version: v1beta1
    group: couchbase.btburnett.com
    path: spec/cluster/clusterRef/name
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: CouchbaseIndexSet
    version: v1beta1
    group: couchbase.btburnett.com
    path: spec/cluster/clusterRef/secretName
  - kind: CouchbaseIndexSet
    version: v1beta1
    group: couchbase.btburnett.com
    path: spec/cluster/manualRef/secretName

namespace:
- kind: CustomResourceDefinition
  version: v1
  group: apiextensions.k8s.io
  path: spec/conversion/webhook/clientConfig/service/namespace
  create: false

varReference:
- path: metadata/annotations
